<?php

namespace Drupal\trpdownload_api\Annotation;

use Drupal\Component\Annotation\Plugin;

/**
 * Defines tripal_download annotation object.
 *
 * @Annotation
 */
class TripalDownload extends Plugin {

  /**
   * A unique, machine name for this download type.
   *
   * This is used to uniquely identify this implementation and is passed to the
   * plugin manager to retrieve details.
   *
   * This should contain only alphanumeric scharacters and underscores.
   *
   * Example: modulename_toolname
   *
   * @var string
   */
  public $id;

  /**
   * The human-readable name of this download implementation.
   *
   * This will be used in future administrative interfaces and as a default
   * in user-facing pages.
   *
   * Example: Tool Name Data Download
   *
   * @var \Drupal\Core\Annotation\Translation
   *
   * @ingroup plugin_translatable
   */
  public $title;

  /**
   * A human-readable description of the format the downloadable file will be in.
   *
   * This will be used in future administrative interfaces and as a default
   * in user-facing pages.
   *
   * Example: Comma-Separated Values
   *
   * @var \Drupal\Core\Annotation\Translation
   */
  public $format_label;

  /**
   * The suffix for the file that is produced.
   *
   * This will be appended to the generated file after a period and provided
   * to the user.
   *
   * Example: csv
   *
   * @var string
   */
  public $file_suffix;

  /**
   * The description of this download implementation.
   *
   * Example: Provides download of data generated by a given usage of Tool Name in a tabular format.
   *
   * @var \Drupal\Core\Annotation\Translation
   *
   * @ingroup plugin_translatable
   */
  public $description;

}
