
name: PHPUnit
on: [push]

env:
  PKG_NAME: trpdownload_api
  MODULES: "trpdownload_api trpdownload_example"
  SIMPLETEST_BASE_URL: "http://localhost"
  SIMPLETEST_DB: "pgsql://drupaladmin:drupal9developmentonlylocal@localhost/sitedb"
  BROWSER_OUTPUT_DIRECTORY: "/var/www/drupal9/web/sites/default/files/simpletest"

jobs:
  run-tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-version:
          - "8.0"
          - "8.1"
        pgsql-version:
          - "13"
        drupal-version:
          - "9.3.x-dev"
          - "9.4.x-dev"
          - "9.5.x-dev"
          # - "10.0.x-dev"
#        exclude:
#          - php-version: "8.0"
#            pgsql-version: "13"
#            drupal-version: "10.0.x-dev"

    steps:
      # Check out the repo
      - name: Checkout Repository
        uses: actions/checkout@v3
      # Here we pull the development tripaldocker image for this combo in our matrix
      - name: Pull TripalDocker Image
        env:
          IMAGE_TAG: drupal${{ matrix.drupal-version }}-php${{ matrix.php-version}}-pgsql${{ matrix.pgsql-version }}
        run: |
          docker pull tripalproject/tripaldocker:$IMAGE_TAG
      # Just spin up docker the good ol' fashion way
      # mounting our currently checked out package inside the docker container.
      - name: Spin up Docker locally
        env:
          IMAGE_TAG: drupal${{ matrix.drupal-version }}-php${{ matrix.php-version}}-pgsql${{ matrix.pgsql-version }}
        run: |
          docker run --publish=80:80 --name=tripaldocker -tid \
            --volume=`pwd`:/var/www/drupal9/web/modules/$PKG_NAME tripalproject/tripaldocker:$IMAGE_TAG
      # Install the modules
      - name: Install our package in Docker
        run: |
          docker exec tripaldocker service postgresql restart
          docker exec tripaldocker drush en $MODULES --yes
      # Runs the PHPUnit tests.
      - name: Run PHPUnit Tests
        run: |
          docker exec tripaldocker service postgresql restart
          docker exec -e SIMPLETEST_BASE_URL=$SIMPLETEST_BASE_URL \
            -e SIMPLETEST_DB=$SIMPLETEST_DB \
            -e BROWSER_OUTPUT_DIRECTORY=$BROWSER_OUTPUT_DIRECTORY \
            --workdir=/var/www/drupal9/web/modules/$PKG_NAME \
            tripaldocker phpunit
